### ISSUE TITLE
Kotlin file default 

### ISSUE THREAD

**Issue by andihasan97** [Cosmic-Ide/rewrite#18]
I tried cosmicIDE rewrite, my advice when creating a new project the default template is set to kotlin as google has suggested to use kotlin 
![Screenshot_20230425_175312](https://user-images.githubusercontent.com/96150715/234256201-36613d1a-bac0-407d-a840-1c134aa45701.jpg)

**Comment by BlueCatSoftware** [comment]
@andihasan97 so what's your point ?

**Comment by BlueCatSoftware** [comment]
> > @andihasan97 so what's your point ?
> 
> He means to enable the kotlin switch automatically

oh okay
