### ISSUE TITLE
Create project" should also be a sub-fab, just like "Import Project"

### ISSUE THREAD

**Issue by DestroyScript** [Cosmic-Ide/rewrite#31]
The undesirable behavior below(I would like to close the fab.)::

https://github.com/Cosmic-Ide/rewrite/assets/122464646/6c6a4dda-9a6d-4acd-bdf4-e8d8b873c1f7

Example of how it should be:

![images (1)](https://github.com/Cosmic-Ide/rewrite/assets/122464646/7458b3ae-94b6-4af5-9a66-5826d7fadebb)

If you implement my suggestion, I think it would be good to add a shortcut to Settings on the home, like the example below:

![Screenshot_20230603-155402_DSU Sideloader~2](https://github.com/Cosmic-Ide/rewrite/assets/122464646/1aebbe93-8f2b-4f1a-bbdf-d848aaaf2111)

**Comment by PranavPurwar** [comment]
> The undesirable behavior below(I would like to close the fab.)::
> 
>  screen-20230603-154714.mp4 
> Example of how it should be:
> 
> ![images (1)](https://user-images.githubusercontent.com/122464646/243125429-7458b3ae-94b6-4af5-9a66-5826d7fadebb.jpeg)
> 
> If you implement my suggestion, I think it would be good to add a shortcut to Settings on the home, like the example below:
> 
> ![Screenshot_20230603-155402_DSU Sideloader~2](https://user-images.githubusercontent.com/122464646/243125601-1aebbe93-8f2b-4f1a-bbdf-d848aaaf2111.png)

done
