### ISSUE TITLE
The autocomplete is inconsistent

### ISSUE THREAD

**Issue by DestroyScript** [Cosmic-Ide/rewrite#32]
The auto-complete feature is completely inconsistent. Sometimes it shows all the classes and keywords, and other times it completes correctly, only filtering and displaying what I'm typing. Another issue is that it can't complete methods from imported classes, for example, from Java itself, the "System" class doesn't autocomplete or show anything when I type "System." (And also, if I type "whi" (and then click on "while"), it becomes "whiwhile" sometimes, but other times it replaces correctly.) Anyway, the auto-complete feature is very inconsistent; it works correctly when it wants to and it also lacks the ability to automatically import classes. For instance, if I type "Array," it will show all the classes, but it won't automatically import the one I click on.

**Comment by PranavPurwar** [comment]
Please recreate the issue in main repository if its still there.
