### ISSUE TITLE
[Feature] : repository clone option

### ISSUE THREAD

**Issue by andihasan97** [Cosmic-Ide/rewrite#53]
please add an option to clone repository at the beginning, so after clone the project will be saved in the initial project list 
![Screenshot_20230715_230513](https://github.com/Cosmic-Ide/rewrite/assets/96150715/1fb843f4-a3d2-4d56-97ec-d34a8482e2ea)

**Comment by PranavPurwar** [comment]
Added

**Comment by andihasan97** [comment]
> Added

thank you
