### ISSUE TITLE
[bug] crashes when process is cloning public repository

### ISSUE THREAD

**Issue by andihasan97** [Cosmic-Ide/rewrite#56]
when I try to clone the public repository the app crashes while the process is running, and there are files that are lacking so they haven't been completely cloned, and file trees that don't consistently display file and folder names like those at the end of the video 

https://github.com/Cosmic-Ide/rewrite/assets/96150715/af07a7cc-2721-4a78-9616-d7a4961f145e

**Comment by PranavPurwar** [comment]
The file tree bug is known and would be fixed soon. For the crash, I tested with the latest snapshot on Android 9 and it worked fine. What snapshot version are you using?

**Comment by andihasan97** [comment]
> The file tree bug is known and would be fixed soon. For the crash, I tested with the latest snapshot on Android 9 and it worked fine. What snapshot version are you using?

i am using Android 11 vivo 1901, rewrite from latest github action

**Comment by PranavPurwar** [comment]
Can you send the crash log here?

**Comment by andihasan97** [comment]
> Can you send the crash log here?

after I tried the last commit it didn't crash, but it still crashes when cloning the private repository, I'll send the logs on another issue
