### ISSUE TITLE
[bug] unicode code not working 

### ISSUE THREAD

**Issue by andihasan97** [Cosmic-Ide/rewrite#60]
I wrote down the unicode code for the symbol for degrees, minutes, seconds, but when I run it, it displays Korean/Japanese characters
![IMG_20230723_160404](https://github.com/Cosmic-Ide/rewrite/assets/96150715/f595420a-5370-4d51-a377-8cfe0c32d14e)
![IMG_20230723_160419](https://github.com/Cosmic-Ide/rewrite/assets/96150715/0425fc3b-f590-4494-ba29-5708a01f9d31)

it should be like this 
![IMG_20230723_162636](https://github.com/Cosmic-Ide/rewrite/assets/96150715/c206d918-cc57-473e-93be-f8a8ccf43162)

**Comment by PranavPurwar** [comment]
Please recreate the issue in main repository
