### ISSUE TITLE
Feat: Implement Roboto Regular Font for Enhanced Visuals

### ISSUE THREAD

**Issue by ArjunaKumarMohanta** [Cosmic-Ide/rewrite#74]
Use Roboto Regular font throughout your app, except for the code editor font style, to ensure it looks visually appealing on Android devices. I believe this will be effective in enhancing the overall user experience.

Download link: https://fonts.google.com/specimen/Roboto?query=Roboto

@PranavPurwar

**Comment by PranavPurwar** [comment]
Enabled inter font throughout the app
